query {
    delivery {
        data {
            attributes {
                delivery_mail_data {
                    label
                    price
                    delivery_time
                }
                closest_delivery_date
            }
        }
    }
}
