query {
    promoCode {
        data {
            attributes {
                promo_codes(filters: { code: { eq: "sdsds" } }) {
                    type
                    discount
                    code
                }
            }
        }
    }
}
